### PR TITLE
remove —no-cache-dir arg

### PR DESCRIPTION
**Pull request by minrk**
caches are good! disabling cache should ~only be used when building docker images

### CODE REVIEW

**Comment by yuvipanda** [comment]
It puts things in /root, which fails in the init-script stage in some places some of the time. This is why I have it disabled in the bootstrap / installer stage! I'll document that..

**Comment by yuvipanda** [comment]
It looks like conda might still be putting stuff in /root, I'll investigate.

**Comment by minrk** [comment]
Ah, that's weird. Probably down to where $HOME is, which is typicall /root for root. Where does that fail?

**Comment by yuvipanda** [comment]
I had it fail with a 'root file system readonly' error on DigitalOcean with a traceback to /root, but can't reproduce it anymore. I'll just merge this now and see if it pops up again.

**Comment by yuvipanda** [comment]
There's a bunch of '  Failed building wheel for pyyaml' in there now, because wheel building fails. I'm tempted to revert this for now.

**Pull request merged**
